import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Layout from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <Layout home>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div className={styles.center}>
                    <Image
                        className={styles.logo}
                        src="/next.svg"
                        alt="Next.js Logo"
                        width={180}
                        height={37}
                        priority
                    />
                </div>

                <div className={styles.grid}>
                    <Link
                        legacyBehavior
                        href="/posts/page1"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <a>
                            <h2>
                                Google Calendar <span>-&gt;</span>
                            </h2>
                        </a>
                    </Link>
                </div>
            </main>
        </Layout>
    );
}
